# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink: pretty
disqus: datamixblog
markdown: kramdown
highlighter: rouge
rss: true
kramdown:
  input: GFM

# Setup
title:               DataMiX Blog
tagline:             "Le blog de l'équipe Data de Microeconomix"
description:         'Ceci est le blog des économistes, économètres et data scientists de <a href="http://www.microeconomix.fr">Microeconomix</a>'
url:                 http://microeconomixblog.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Ignacio Inoa
  url:               https://twitter.com/InoaIgnacio
  email:             ignacio.inoa@microeconomix.com

# Custom vars
version:             1.0.0

footer-links:
  email: ignacio.inoa@microeconomix.com
  github: microeconomixblog
  twitter: microeconomix

