# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink: pretty
disqus: datamixblog
markdown: kramdown
highlighter: rouge
rss: true
kramdown:
  input: GFM

# Setup
title:               DataMiX Blog
tagline:             "Le blog de l'équipe Data de Microeconomix"
description:         'Ceci est le blog des économistes, économètres et data scientists de <a href="http://www.microeconomix.fr">Microeconomix</a>'
url:                 http://microeconomixblog.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Ignacio Inoa
  url:               https://twitter.com/InoaIgnacio
  email:             ignacio.inoa@microeconomix.com
  email_md5:         b7ea3d21d483b2e40ce76c06be6e0c24
  github:            microeconomixblog
  twitter:           microeconomix
  linkedin:          https://fr.linkedin.com/in/ignacio-a-inoa-470ba770

# Custom vars
version:             1.0.0



